from setuptools import find_packages, setup

setup(
    name="nwa-stdlib",
    version="1.0.12",
    packages=find_packages(),
    url="https://gitlab.surfnet.nl/automation/nwa-stdlib",
    classifiers=["License :: OSI Approved :: Apache2 License", "Programming Language :: Python :: 3.x"],
    license="Apache2",
    author="Automation",
    author_email="automation-nw@surfnet.nl",
    description="NWA standard library.",
    install_requires=[
        "flask>=1.0.0",
        "requests>=2.19.0",
        "redis==3.5.3",
        "hiredis>=1.0.1",
        "ruamel.yaml~=0.16.10",
        "structlog==20.1.0",
    ],
    tests_require=[
        "pytest",
        "flake8",
        "black",
        "isort",
        "flake8-bandit",
        "flake8-bugbear",
        "flake8-comprehensions",
        "flake8-docstrings",
        "flake8-logging-format",
        "flake8-pep3101",
        "flake8-print",
        "mypy",
        "mypy_extensions",
        "fakeredis",
        "pre-commit",
    ],
)
